services:
  controller:
    build: .
    network_mode: "host"
    privileged: true
    ipc: "host"
    environment:
      - ROS_DOMAIN_ID=42
      - ROS_LOCALHOST_ONLY=0
    volumes:
      - ./src/image_processor_pkg:/ros2_ws/src/image_processor_pkg
    command: >
      bash -c "
        source /opt/ros/humble/setup.bash &&
        colcon build --symlink-install --packages-select image_processor_pkg &&
        source install/setup.bash &&
        ros2 run image_processor_pkg controller_node.py --ros-args --params-file /ros2_ws/src/image_processor_pkg/config/params.yaml
      "
